const axios = require('axios');

module.exports = [{
    command: ['fluxai'],
    alias: ['flux', 'imagine'],
    description: 'Generate an image using Flux AI.',
    category: 'Ai',
    filename: __filename,
    
    async execute(m, { ednut, q, reply, from }) {
        try {
            if (!q) return reply('Please provide a prompt for the image.');
            
            await reply('> *CREATING IMAGINE ...🔥*');
            
            const apiUrl = 'https://api.siputzx.my.id/api/ai/flux?prompt=' + encodeURIComponent(q);
            const response = await axios.get(apiUrl, { responseType: 'arraybuffer' });
            
            if (!response?.data) return reply('Error: The API did not return a valid image. Try again later.');
            
            const imageBuffer = Buffer.from(response.data, 'binary');
            
            await ednut.sendMessage(from, {
                image: imageBuffer,
                caption: '💸 *Imagine Generated By Zed-Bot* 🚀\n✨ Prompt: *' + q + '*'
            });
            
        } catch (error) {
            console.error('FluxAI Error:', error);
            reply('An error occurred: ' + (error.response?.data?.message || error.message || 'Unknown error'));
        }
    }
}];